// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybrnstgyapxdnlqvblaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlicm5zdGd5YXB4ZG5scXZibGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MDc3NzIsImV4cCI6MjA3MjA4Mzc3Mn0.ao3SJjKv2KVXXsYqnl51GEdFlwqfhIh1QgACc5B5zYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});